name: Test and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

jobs:
  rubocop-rspec:
    name: rubocop and rspec, then deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: application setup
        run: |
          docker-compose exec -T rails bundle install
          docker-compose exec -T rails yarn install

      - name: database setup
        run: |
          docker-compose exec -T rails rails db:create
          docker-compose exec -T rails rails db:migrate

      - name: rubocop
        run: docker-compose exec -T rails bundle exec rubocop

      - name: rspec
        run: docker-compose exec -T rails bundle exec rspec

      - name: prepare ssh key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name: run server script
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} "~/deploy.sh"
